service:
  name: aws-nodejs-typescript

package:
  individually: true

custom:
  ${file(config/custom.yml)}

# Add the serverless-webpack plugin
plugins:
  - serverless-pseudo-parameters
  - serverless-webpack

environment:
  ${file(config/environments/${opt:stage, 'sandbox'}.yml)}

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: ${opt:stage, 'sandbox'}
  iamRoleStatements:
    ${file(config/role-statements/common.yml)}

functions:
  - ${file(config/functions/hello.yml)}

resources:
  - ${file(config/resources/common.yml)}
