service:
  name: aws-nodejs-typescript

package:
  individually: true

custom:
  ${file(config/custom.yml)}

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'sandbox'}
  iamRoleStatements:
    ${file(config/role-statements/common.yml)}
  environment:
    ${file(config/environments/${opt:stage, 'sandbox'}.yml)}

functions:
  - ${file(config/functions/hello.yml)}

resources:
  - ${file(config/resources/api-gateway.yml)}
  - ${file(config/resources/common.yml)}
